name = "nuttertools"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "gamestore"
database_id = "c86eddfb-dcc5-4904-8bfd-c337b1691ca3"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "gamestore"
